[package]
authors = ["koka <koka.code@gmail.com>"]
name = "geolocation"
version = "0.1.0"
[dependencies]
futures = "0.1.17"
hyper = "0.11.6"
hyper-tls = "0.1.2"
serde = "1.0.20"
serde_derive = "1.0.20"
serde_json = "1.0.6"
tokio-core = "0.1.10"
